//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string text { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
