//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLove
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coursachEntities : DbContext
    {
        private static coursachEntities context;
        public coursachEntities()
            : base("name=coursachEntities")
        {
        }

        public static coursachEntities GetContext()
        {
            if (context == null)
            {
                context = new coursachEntities();
            }
            return context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_> Admin_ { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Era> Era { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Travels> Travels { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
    }
}
