//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travels
    {
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<int> era_id { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual Era Era { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
