//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLove.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coursachEntities : DbContext
    {
        public coursachEntities()
            : base("name=coursachEntities")
        {
        }

        private static coursachEntities context;

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static coursachEntities GetContext()
        {
            if (context == null)
            {
                context = new coursachEntities();
            }
            return context;
        }

        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Era> Era { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Travel> Travel { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
    }
}
